-- custom app roles types
CREATE TYPE public.app_role AS enum ('admin');

-- USER ROLES
CREATE TABLE public.user_roles (
  id bigint generated by DEFAULT AS identity PRIMARY KEY,
  user_id uuid REFERENCES public.users ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  UNIQUE (user_id, role)
);
COMMENT ON TABLE public.user_roles IS 'Application roles for each user.';

-- authorize with role-based access control (RBAC)
CREATE FUNCTION public.authorize(user_id uuid) RETURNS boolean AS $ $ declare bind_permissions int;
BEGIN
SELECT
  count(*)
FROM
  public.user_roles
WHERE
  user_roles.user_id = authorize.user_id INTO bind_permissions;
RETURN bind_permissions > 0;
END;
$$ language plpgsql SECURITY DEFINER;

-- Secure the tables
ALTER TABLE
  public.user_roles enable ROW LEVEL SECURITY;

CREATE policy "Allow individual read access" ON public.user_roles FOR
SELECT
  USING (auth.uid() = user_id);