-- custom app roles types
create type public.app_role as enum ('admin');

-- USER ROLES
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references public.users on delete cascade not null,
  role      app_role not null,
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- authorize with role-based access control (RBAC)
create function public.authorize(
  user_id uuid
)
returns boolean as $$
declare
  bind_permissions int;
begin
  select count(*)
  from public.user_roles
  where user_roles.user_id = authorize.user_id
  into bind_permissions;
  
  return bind_permissions > 0;
end;
$$ language plpgsql security definer;

-- Secure the tables
alter table public.user_roles enable row level security;
create policy "Allow individual read access" on public.user_roles for select using ( auth.uid() = user_id );